# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: de

pipeline:
  - name: SpacyNLP
    model: "de_core_news_md"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 200
  - name: FallbackClassifier
    threshold: 0.7
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
  - name: MappingPolicy
  - name: RulePolicy